# Generated by Django 4.1.4 on 2023-01-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=120)),
                ('Pphone', models.IntegerField()),
                ('medicalHistory', models.TextField()),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.bg')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=120, verbose_name='Name')),
                ('Dphone', models.IntegerField()),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.bg')),
            ],
        ),
    ]
