# Generated by Django 4.1.4 on 2023-01-18 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
