# Generated by Django 4.1.4 on 2023-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0002_donor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='DateUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='medicalHistory',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medicalHistory',
            field=models.TextField(default=None),
        ),
    ]
