# Generated by Django 4.1.4 on 2023-02-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_donor_dateupdate_donor_is_active_donor_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg',
            name='bloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=100),
        ),
    ]
