# Generated by Django 4.1.4 on 2023-02-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0005_rename_medicalhistory_donor_healthstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctorName',
            field=models.CharField(default='Dr. John Doe', max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.CharField(default='General Hospital', max_length=120),
        ),
    ]
