# Generated by Django 4.1.4 on 2023-02-24 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0007_patient_date_patient_dateupdate_alter_donor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 24, 9, 17, 30, 285457, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
