# Generated by Django 4.1.4 on 2023-02-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0008_alter_donor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='location',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
