# Generated by Django 4.1.4 on 2023-03-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0009_alter_donor_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bg',
            options={'verbose_name': 'Blood Group', 'verbose_name_plural': 'Blood Groups'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
