# Generated by Django 4.1.4 on 2023-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0010_alter_bg_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg',
            name='bloodGroup',
            field=models.CharField(choices=[('Apositive', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=100),
        ),
    ]
