# Generated by Django 4.1.4 on 2023-03-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0011_alter_bg_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg',
            name='bloodGroup',
            field=models.CharField(choices=[('A+', 'Apositive'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=100),
        ),
    ]
