# Generated by Django 4.1.4 on 2023-03-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0013_alter_bg_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='healthApp.bg'),
        ),
    ]
