# Generated by Django 4.1.4 on 2023-03-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0014_alter_donor_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Pname',
            field=models.CharField(max_length=120, verbose_name='Patient'),
        ),
    ]
